#!/usr/bin/env zsh
rawsel=$(fd -H -t d -d 3 . /mnt/e /home/taarkik /mnt/f | fzf)

name=$(basename $rawsel)

if [[ -z $rawsel ]]; then
  exit 0
fi

selected=$(echo $rawsel | sed -e 's,[/ ]*$,,g')


selected_name=$(basename $selected | tr . _ )

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected
  exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
  tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
